### ISSUE TITLE
Log manyToMany tables

### ISSUE THREAD

**Issue by n-osennij** [alkhachatryan/laravel-loggable#3]
I have manyToManyTable:

> Admissions -> admissions_tag <- Tags

I use loggable in `Admission `model and in `Tag `model too.

When I post to Admission (create action) I can pass to created admission tags.

```
class AdmissionController extends Controller
{
	public function store(Request $request)
    {
        // validation
        // ... result of validation in $attributes.

        $admission = new Admission($attributes);
        $admission->save();

        if (!empty($request->tags)) {
            $admission->tags()->sync($request->tags);
        }

        return redirect()
            ->action('AdmissionController@index')
            ->with('status', 'sucess');
    }
}
```
As you can see, first I save data to `admissions `table, then I associate new `tags `to this `admission`.
How can I log data In related table? Is in possible to log related data?

**Comment by alkhachatryan** [comment]
>  Is in possible to log related data?

At this moment the Loggable package works only for CRUD structure (Create, Update and Delete, without Read)

This is first release and I have an ideas for relational structure logging.

Feel free to contribute and open your PR here.
